# Generated by Django 6.1 on 2026-08-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_company_numbers(apps, schema_editor):
    database = schema_editor.connection.alias
    for model_name, field_name in (("Client", "patient_number"), ("Membership", "employee_number")):
        model = apps.get_model("app", model_name)
        records = model.objects.using(database)
        company_ids = records.order_by().values_list("company_id", flat=True).distinct()
        for company_id in company_ids:
            ids = records.filter(company_id=company_id).order_by("created_at", "id").values_list("id", flat=True)
            for number, item_id in enumerate(ids, 1):
                records.filter(pk=item_id).update(**{field_name: number})
    if schema_editor.connection.vendor == "postgresql":
        # AddField also defers creation of the primary_doctor index until the
        # schema editor exits. Fire pending constraint triggers before that DDL,
        # preserving the migration's all-or-nothing transaction.
        schema_editor.connection.check_constraints()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_service_duration_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['patient_number', 'last_name', 'first_name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='client',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='patient_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_clients', to='app.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='employee_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'patient_number'), name='unique_company_patient_number'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('company', 'employee_number'), name='unique_company_employee_number'),
        ),
        # Both new number columns are nullable, so constraints can be installed
        # before backfilling. Keep all ALTER TABLE operations ahead of data writes:
        # PostgreSQL queues deferred FK trigger events during the updates and
        # refuses subsequent ALTER TABLE operations until those events are fired.
        migrations.RunPython(assign_company_numbers, migrations.RunPython.noop),
    ]
